
#' Merge split string columns into origin column. By default foreign splits long strings into several columns. 
#' This is a workaround to fix this problem by combining columns split columns into one.
#' 
#' Columns are merged by the following rules:
#' 1. columns must be character
#' 2. columns must be in sequential order
#' 3. origin column names are extended by 0-9 and A-Z. If a matching variable is found in sequential column order and is character, columns will be merged.
#' 4. if there is a punct character in column name, everything after punct is take into account (e.g. V110_TE will be merged with V110_0 when both are character and in sequential order)

#' @title merge split string columns into origin column
#' @param x data.frame
#' @param exclude character vector with variables not taken into account
#' @param verbose print messages to console
#' @returns data.frame
#' @export
i_fix_char_cols <- function(x, exclude = NULL, verbose = TRUE){
  
  if(!is.null(exclude) && (!is.atomic(exclude) && !is.character(exclude))){
    stop("exclude must be character vector")
  }
  
  # get all column names
  col_names <- names(x)[!names(x) %in% exclude]
  # get character columns
  char_cols <- col_names[unlist(lapply(x, is.character))]
  
  # find columns that were split due to long string values by name-extensions generated by foreign
  cols_to_merge <- sapply(col_names, function(x){
    ret <- NULL
    pos_x <- which(col_names == x)
    x_extensions1 <- paste0(x, c(0:9, LETTERS)) 
    x_extensions2 <- paste0(sub("(?<=[[:punct:]])[a-zA-Z].*", "", x, perl = TRUE), c(0:9, LETTERS))
    x_extensions <- c(x_extensions1, x_extensions2)
    x_extended_vars <- col_names[col_names %in% x_extensions & col_names %in% char_cols]
    if(length(x_extended_vars) > 0){
      pos_x_ext_vars <- sort(which(col_names %in% x_extended_vars))  
      ext_var_is_in_sequence <- apply(array(pos_x_ext_vars), MARGIN = 1, FUN = function(y) (y-1) %in% c(pos_x, pos_x_ext_vars) )
      pos_x_ext_vars <- pos_x_ext_vars[ext_var_is_in_sequence]
      if(length(pos_x_ext_vars) > 0){
        ret <- col_names[pos_x_ext_vars]
      }
    }
    ret
  }, USE.NAMES = TRUE, simplify = FALSE)
  cols_to_merge <- cols_to_merge[unlist(lapply(cols_to_merge, function(x) !is.null(x)))]
  
  # merge split string columns into origin column
  if(length(cols_to_merge) > 0){
    for(i in names(cols_to_merge)){
      if(verbose){
        message("merge ", paste0(cols_to_merge[[i]], collapse = ", "), " into ", i)
      }
      attr_temp <- attributes(x[[i]])
      merge_cols <- subset(x, select = c(i, cols_to_merge[[i]]))
      merged_col <- do.call(paste0, as.list(merge_cols))  
      x[[i]] <- merged_col
      attributes(x[[i]]) <- attr_temp
    }
    x <- subset(x, select = -which(names(x) %in% unlist(cols_to_merge)))
  }
  
  return(x)
}